Repository AgnostiqHQ/covalent, pull requests merged in 2022-04, with the labels that each got.

#269 Replace TemporaryFile with io.BytesIO in `update_result`
  CHANGELOG.md
  refactor/results/app/api/api_v0/endpoints/workflow.py
Labels: covalent-data

#307 supporting batch delete
  CHANGELOG.md
  refactor/data/app/api/api_v0/endpoints/fs.py
  refactor/data/app/core/localstoragebackend.py
  refactor/data/app/schemas/fs.py
  refactor/data/openapi.yaml
  refactor/results/app/api/api_v0/endpoints/workflow.py
  refactor/results/app/schemas/workflow.py
  refactor/results/openapi.yaml
Labels: feature

#315 improving dockerignore
  .dockerignore
  CHANGELOG.md
Labels: devops

#285 adding batch cancel API endpoint
  CHANGELOG.md
  refactor/dispatcher/app/api/api_v0/endpoints/workflow.py
  refactor/dispatcher/app/schemas/__init__.py
  refactor/dispatcher/app/schemas/workflow.py
  refactor/dispatcher/openapi.yaml
Labels: feature

#333 pypi uses token
  .github/workflows/pypi.yml
  CHANGELOG.md
Labels: devops

#364 Update/fix the Dockerfiles to use multi-stage builds to reduce container image sizes
  CHANGELOG.md
  docker-compose.yml
  refactor/client_side/__init__.py
  refactor/client_side/example_dispatch.py
  refactor/data/Dockerfile
  refactor/dispatcher/Dockerfile
  refactor/dispatcher/Dockerfile.queue_consumer
  refactor/queuer/Dockerfile
  refactor/results/Dockerfile
  refactor/runner/Dockerfile
  refactor/ui_backend/Dockerfile
  tests/requirements.txt
Labels: priority / high

#387 Updated the "How to create a custom executor" notebook.
  CHANGELOG.md
  doc/source/how_to/execution/creating_custom_executors.ipynb
Labels: documentation

#426 Changing hypens to underscores
  .github/workflows/publish_develop.yml
  .github/workflows/publish_master.yml
  CHANGELOG.md
Labels: bug

#412 Update concepts page
  CHANGELOG.md
  doc/source/concepts/concepts.rst
  doc/source/concepts/images/status_check.png
  doc/source/concepts/images/transport_graph.png
Labels: documentation

#416 Fix quantum chemistry tutorial
  CHANGELOG.md
  doc/source/tutorials/quantum_chemistry/graphs/compute_energy.png
  doc/source/tutorials/quantum_chemistry/graphs/vary_distance.png
  doc/source/tutorials/quantum_chemistry/nitrogen_copper_interaction.ipynb
Labels: documentation

#425 Update ml tutorials
  CHANGELOG.md
  doc/source/tutorials/astronomy/star_tracker.ipynb
  doc/source/tutorials/machine_learning/classical_quantum_svm.ipynb
  doc/source/tutorials/machine_learning/mnist_classifier.ipynb
  doc/source/tutorials/quantum_gravity/spacetime_classification.ipynb
Labels: documentation

#400 How-to fixes
  CHANGELOG.md
  doc/source/how_to/collection/query_electron_execution_result.ipynb
  doc/source/how_to/collection/query_lattice_execution_result.ipynb
  doc/source/how_to/collection/query_multiple_lattice_execution_results.ipynb
  doc/source/how_to/config/customization.ipynb
  doc/source/how_to/execution/cancel_dispatch.ipynb
  doc/source/how_to/execution/choosing_conda_environments.ipynb
  doc/source/how_to/execution/choosing_executors.ipynb
  doc/source/how_to/execution/creating_custom_executors.ipynb
  doc/source/how_to/execution/execute_individual_electron.ipynb
  doc/source/how_to/execution/execute_lattice.ipynb
  doc/source/how_to/execution/execute_multiple_lattices.ipynb
  doc/source/how_to/execution/execute_sublattice.ipynb
  doc/source/how_to/execution/synchronize_lattice.ipynb
  doc/source/how_to/orchestration/add_constraints_to_lattice.ipynb
  doc/source/how_to/orchestration/construct_c_task.ipynb
  doc/source/how_to/orchestration/construct_lepton.ipynb
  doc/source/how_to/status/query_electron_execution_status.ipynb
  doc/source/how_to/status/query_lattice_execution_status.ipynb
  doc/source/how_to/status/query_lattice_execution_time.ipynb
Labels: documentation

#443 Fix cancel workflow bug
  CHANGELOG.md
  covalent_dispatcher/app/api/api_v0/endpoints/workflow.py
  covalent_dispatcher/app/core/cancel_workflow.py
  covalent_dispatcher/app/core/dispatch_workflow.py
  covalent_dispatcher/app/core/update_workflow.py
  covalent_dispatcher/app/core/utils.py
  covalent_runner/app/api/api_v0/endpoints/task.py
  covalent_runner/app/core/execution.py
  tests/cancel_workflow_example.ipynb
Labels: covalent-dispatcher, covalent-executor, lattice, result, priority / high, covalent-runner
