Repository AgnostiqHQ/covalent, pull requests merged in 2022-07, with the labels that each got.

#833 removing matplotlib and draw_inline
  CHANGELOG.md
  covalent/_workflow/lattice.py
  requirements.txt
  tests/workflow_stack_test.py
Labels: dependencies

#851 improving the dockerfile
  .github/workflows/docker.yml
  CHANGELOG.md
  Dockerfile
Labels: devops, Team East

#834 fixing cova-covalent conflict
  CHANGELOG.md
  setup.py
Labels: bug

#887 removing video
  CHANGELOG.md
  doc/source/index.rst
Labels: hotfix

#896 Second Attempt at Resolving 693
  CHANGELOG.md
  covalent/_shared_files/utils.py
  covalent/executor/base.py
  covalent/executor/executor_plugins/dask.py
  covalent/executor/executor_plugins/local.py
  covalent_dispatcher/_core/execution.py
  tests/covalent_dispatcher_tests/_core/execution_test.py
  tests/covalent_tests/choose_executor_test.py
  tests/covalent_tests/executor/base_test.py
  tests/covalent_tests/executor/executor_plugins/dask_test.py
  tests/covalent_tests/executor/executor_plugins/local_test.py
  tests/requirements.txt
  tests/workflow_stack_test.py
Labels: stale-exempt

#822 Isolating code coverage reports
  .github/workflows/tests.yml
  CHANGELOG.md
  tests/covalent_tests/electron_return_value_test.py
  tests/covalent_tests/workflow_stack_test.py
Labels: Team West, stale-exempt

#827 adding bash decorator
  .github/workflows/tests.yml
  CHANGELOG.md
  covalent/__init__.py
  covalent/_workflow/lepton.py
  covalent/leptons/__init__.py
  tests/covalent_tests/workflow/lepton_test.py
  tests/functional_tests/lepton_test.py
Labels: feature, Team East

#848 Implement static wait for
  CHANGELOG.md
  covalent/__init__.py
  covalent/_workflow/electron.py
  doc/source/concepts/concepts.rst
  tests/covalent_tests/workflow_stack_test.py
Labels: Team West, Stale

#940 Fixing covalent pre-release
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: Team West
