Repository AgnostiqHQ/covalent, pull requests merged in 2022-05, with the labels that each got.

#461 Dask related fixes and optimizations
  covalent/executor/executor_plugins/local.py
  covalent_dispatcher/__init__.py
  covalent_dispatcher/_cli/service.py
  covalent_dispatcher/_core/execution.py
  covalent_dispatcher/entry_point.py
  covalent_ui/app.py
Labels: covalent-dispatcher

#511 enable CovalentOpsBot
  .github/workflows/badges.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql.yml
  .github/workflows/hotfix.yml
  .github/workflows/publish_develop.yml
  .github/workflows/publish_master.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: cloud

#454 Hotfix action fix
  .github/workflows/hotfix.yml
  CHANGELOG.md
Labels: cloud

#424 Updated .env location to $HOME/.cache/covalent. Updated CHANGELOG
  CHANGELOG.md
  covalent/_cli/service.py
  covalent/_cli/supervisord.template.conf
  covalent/_shared_files/config.py
  covalent_data/app/core/config.py
  covalent_dispatcher/app/core/config.py
  covalent_queuer/app/core/config.py
  covalent_results/app/core/config.py
  covalent_runner/app/core/config.py
  covalent_ui/app/core/config.py
  setup.py
Labels: cloud

#432 Health & Readiness endpoints
  CHANGELOG.md
  covalent_data/app/api/api_v0/endpoints/fs.py
  covalent_data/app/api/health.py
  covalent_data/main.py
  covalent_dispatcher/app/api/health.py
  covalent_dispatcher/main.py
  covalent_dispatcher/tests/app/api/health_test.py
  covalent_dispatcher/tests/conftest.py
  covalent_queuer/app/api/health.py
  covalent_queuer/app/core/config.py
  covalent_queuer/main.py
  covalent_queuer/tests/app/core/queuer_test.py
  covalent_results/app/api/health.py
  covalent_results/app/core/db.py
  covalent_results/main.py
  covalent_results/tests/app/api/health_test.py
  covalent_runner/app/api/health.py
  covalent_runner/main.py
  covalent_runner/tests/app/api/health_test.py
  covalent_runner/tests/conftest.py
  covalent_ui/app/api/health.py
  covalent_ui/main.py
  covalent_ui/tests/app/api/health_test.py
Labels: cloud

#525 Adding mysql support
  CHANGELOG.md
  covalent/.env.example
  covalent_results/Dockerfile
  covalent_results/app/api/api_v0/endpoints/workflow.py
  covalent_results/app/core/config.py
  covalent_results/app/core/db.py
  covalent_results/app/schemas/workflow.py
  covalent_results/requirements/dist.txt
  covalent_results/tests/main_test.py
  docker-compose.yml
Labels: feature, cloud
