Repository AgnostiqHQ/covalent, pull requests merged in 2022-02, with the labels that each got.

#88 requiring todays date in the changelog
  .github/workflows/publish_master.yml
  .github/workflows/version.yml
  CHANGELOG.md
  VERSION
Labels: devops

#67 testing multiple versions in pipeline
  .github/workflows/tests.yml
  CHANGELOG.md
  VERSION
  doc/source/getting_started/compatibility.rst
  doc/source/getting_started/index.rst
  tests/requirements.txt
Labels: test, devops

#94 Create codeql-analysis.yml
  .github/workflows/codeql.yml
  CHANGELOG.md
  VERSION
Labels: devops

#103 added codeowners
  .github/CODEOWNERS
  CHANGELOG.md
  VERSION
Labels: devops

#114 Basic structure to write a beginner tutorial
  CHANGELOG.md
  VERSION
  doc/source/tutorials/tutorial_guide.rst
  doc/source/tutorials/tutorials.rst
Labels: documentation, feature

#135 Adding support for args throughout covalent
  CHANGELOG.md
  VERSION
  covalent/_dispatcher_plugins/local.py
  covalent/_results_manager/result.py
  covalent/_results_manager/utils.py
  covalent/_shared_files/utils.py
  covalent/_workflow/electron.py
  covalent/_workflow/lattice.py
  covalent/_workflow/transport.py
  covalent/executor/base.py
  covalent/executor/executor_plugins/local.py
  covalent_dispatcher/_core/execution.py
  tests/covalent_tests/executor/base_test.py
  tests/covalent_tests/executor/executor_plugins/local_test.py
  tests/covalent_tests/workflow/transport_test.py
  tests/workflow_stack_test.py
Labels: feature, covalent-dispatcher, covalent-executor, electron, lattice, transport-graph

#133 fixing codeowners
  .github/CODEOWNERS
  CHANGELOG.md
  VERSION
Labels: bug, devops

#139 fixing path
  CHANGELOG.md
  VERSION
  covalent/executor/__init__.py
  tests/workflow_stack_test.py
Labels: bug, covalent-executor
