Repository AgnostiqHQ/covalent, pull requests merged in 2022-09, with the labels that each got.

#1189 Add V12 migration script
  CHANGELOG.md
  covalent_migrations/versions/26d71848a404_v12.py
Labels: Team West

#1122 1080 create nightly ci
  .github/workflows/changelog.yml
  .github/workflows/conda_build.yml
  .github/workflows/license.yml
  .github/workflows/nightly.yml
  .github/workflows/test_matrix.json
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: devops

#1054 improving prerelease workflows
  .github/workflows/release_candidate.yml
  CHANGELOG.md
Labels: priority::high

#1167 modifying actions to use OIDC
  .github/workflows/badges.yml
  .github/workflows/benchmark.yml
  .github/workflows/docker.yml
  .github/workflows/push_to_s3.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
Labels: ready for merge

#1251 Lock config file during config updates
  CHANGELOG.md
  covalent/_shared_files/config.py
  tests/covalent_tests/shared_files/config_test.py
Labels: ready for merge

#1245 Fix benchmark/release workflow
  .github/workflows/benchmark.yml
  .github/workflows/release.yml
  CHANGELOG.md
  tests/stress_tests/benchmarks/cpu_intensive_workflows_test.py
  tests/stress_tests/benchmarks/memory_intensive_workflow_test.py
  tests/stress_tests/benchmarks/parallel_workflows_test.py
  tests/stress_tests/benchmarks/two_node_workflows_test.py
  tests/stress_tests/benchmarks/vertical_workflows_test.py
Labels: ready for merge

#1259 Fix for default executor value setting
  CHANGELOG.md
  covalent/_shared_files/defaults.py
  tests/covalent_tests/shared_files/defaults_test.py
Labels: Team West

#1252 Fix codecov reporting
  .github/workflows/test_matrix.json
  .github/workflows/tests.yml
  CHANGELOG.md
  MANIFEST.in
Labels: ready for merge

#1268 Remove DB dependency from get_all_node_outputs
  CHANGELOG.md
  covalent/_results_manager/result.py
Labels: ready for merge

#1238 #1061 JS hotfix action
  .github/actions/describe/action.yml
  .github/actions/describe/dist/index.js
  .github/actions/describe/dist/licenses.txt
  .github/actions/describe/index.js
  .github/actions/describe/package-lock.json
  .github/actions/describe/package.json
  .github/workflows/hotfix.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: ready for merge

#1254 decouple benchmark workflow from nightly
  .github/workflows/benchmark.yml
  .github/workflows/nightly.yml
  CHANGELOG.md
Labels: ready for merge

#1255 create stable version for stable release
  .github/actions/stable-changelog/action.yml
  .github/actions/stable-changelog/dist/index.js
  .github/actions/stable-changelog/dist/licenses.txt
  .github/actions/stable-changelog/index.js
  .github/actions/stable-changelog/package-lock.json
  .github/actions/stable-changelog/package.json
  .github/workflows/release.yml
  CHANGELOG.md
Labels: ready for merge

#1253 adding new platforms
  .github/workflows/test_matrix.json
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: ready for merge

#1292 Force boilerplate
  .github/workflows/boilerplate.yml
  CHANGELOG.md
Labels: ready for merge
