Repository AgnostiqHQ/covalent, pull requests merged in 2022-08, with the labels that each got.

#949 enabling codecov carryforward
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  codecov.yml
Labels: devops, covalent-os, testing, Team East, improvement

#894 replacing DispatchDB instances with datastore factory
  CHANGELOG.md
  covalent/_data_store/__init__.py
  covalent/_data_store/datastore.py
  covalent/_results_manager/result.py
  covalent/_results_manager/results_manager.py
  covalent/_results_manager/write_result_to_db.py
  covalent/_shared_files/config.py
  covalent/_shared_files/defaults.py
  covalent/_workflows_manager/__init__.py
  covalent/_workflows_manager/workflowsmanager.py
  covalent_dispatcher/_cli/service.py
  covalent_dispatcher/_core/execution.py
  covalent_dispatcher/_db/dispatchdb.py
  covalent_dispatcher/_service/app.py
  covalent_dispatcher/entry_point.py
  doc/source/how_to/collection/query_electron_execution_result.ipynb
  doc/source/how_to/config/customization.ipynb
  doc/source/how_to/execution/cancel_dispatch.ipynb
  doc/source/how_to/execution/execute_sublattice.ipynb
  doc/source/tutorials/quantum_chemistry/microservices/nitrogen_copper_interaction.ipynb
  doc/source/tutorials/quantum_chemistry/nitrogen_copper_interaction.ipynb
  tests/covalent_dispatcher_tests/_cli/service_test.py
  tests/covalent_dispatcher_tests/_core/execution_test.py
  tests/covalent_dispatcher_tests/_service/app_test.py
  tests/covalent_dispatcher_tests/dispatchdb_test.py
  tests/covalent_dispatcher_tests/dispatcher_stack_test.py
  tests/covalent_tests/data_store/data_store_test.py
  tests/covalent_tests/data_store/db_test.py
  tests/covalent_tests/results_manager_tests/results_test.py
  tests/covalent_tests/results_manager_tests/write_result_to_db_test.py
  tests/covalent_tests/shared_files/config_test.py
  tests/covalent_tests/workflow_stack_test.py
Labels: ready for merge

#844 File Transfer Keyword Args
  .pre-commit-config.yaml
  CHANGELOG.md
  covalent/_file_transfer/enums.py
  covalent/_file_transfer/file_transfer.py
  covalent/_file_transfer/strategies/http_strategy.py
  covalent/_file_transfer/strategies/rsync_strategy.py
  covalent/_file_transfer/strategies/transfer_strategy_base.py
  covalent/_workflow/depscall.py
  covalent/_workflow/electron.py
  covalent/_workflow/lepton.py
  covalent/executor/base.py
  tests/covalent_tests/executor/base_test.py
  tests/covalent_tests/executor/executor_plugins/local_test.py
  tests/covalent_tests/file_transfer/strategies/base_strategy_test.py
  tests/covalent_tests/workflow/deps_test.py
  tests/covalent_tests/workflow/lepton_test.py
  tests/covalent_tests/workflow_stack_test.py
  tests/functional_tests/file_transfer_test.py
  tests/functional_tests/lepton_test.py
Labels: Team West, Stale

#969 enhancing test, docker, and release actions
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  Dockerfile
  Makefile
Labels: Team East

#974 Fixing broken tests
  .github/workflows/tests.yml
  CHANGELOG.md
  covalent/executor/base.py
  doc/source/how_to/orchestration/add_pip_dependencies_to_electron.ipynb
  tests/covalent_dispatcher_tests/_core/execution_test.py
  tests/covalent_dispatcher_tests/choose_conda_test.py
  tests/covalent_tests/choose_executor_test.py
  tests/covalent_tests/workflow/lattice_serialization_test.py
  tests/functional_tests/_core/execution_test.py
  tests/functional_tests/_dispatcher_plugins/local_test.py
  tests/functional_tests/basic_dispatcher_test.py
  tests/functional_tests/choose_conda_test.py
  tests/functional_tests/choose_executor_test.py
  tests/functional_tests/dask_cluster_cli_test.py
  tests/functional_tests/dask_executor_test.py
  tests/functional_tests/data.py
  tests/functional_tests/dispatcher_server_test.py
  tests/functional_tests/dispatcher_stack_test.py
  tests/functional_tests/electron_return_value_test.py
  tests/functional_tests/init_test.py
  tests/functional_tests/lepton_test.py
  tests/functional_tests/workflow_stack_test.py
Labels: test

#966 Fix config overwriting
  CHANGELOG.md
  covalent/_shared_files/defaults.py
  covalent_dispatcher/_cli/service.py
  covalent_dispatcher/_service/app_dask.py
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: ready for merge

#907 #882 S3 File Transfer Strategy
  CHANGELOG.md
  covalent/_file_transfer/strategies/__init__.py
  covalent/_file_transfer/strategies/s3_strategy.py
  doc/source/concepts/concepts.rst
  doc/source/how_to/orchestration/file_transfers_for_workflows.ipynb
  setup.py
  tests/covalent_tests/file_transfer/strategies/s3_strategy_test.py
Labels: Team West

#897 add abstract setup/teardown executor hooks
  CHANGELOG.md
  covalent/executor/base.py
  covalent/executor/executor_plugins/dask.py
  tests/covalent_tests/executor/base_test.py
Labels: feature, covalent-executor, Stale

#987 adding covalent config cli with tests
  CHANGELOG.md
  covalent_dispatcher/_cli/cli.py
  covalent_dispatcher/_cli/service.py
  tests/covalent_dispatcher_tests/_cli/cli_test.py
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: feature

#928 check for both uppercase/lowercase executor plugin names, update log
  CHANGELOG.md
  covalent/executor/__init__.py
  covalent/executor/executor_plugins/dask.py
  covalent/executor/executor_plugins/local.py
  tests/covalent_dispatcher_tests/_cli/service_test.py
  tests/covalent_tests/executor/init_test.py
Labels: stale-exempt

#994 fix import bug
  CHANGELOG.md
  covalent/executor/__init__.py
Labels: bug

#806 rtd landing page enhancement
  CHANGELOG.md
  doc/source/_static/covalent_platform.svg
  doc/source/index.rst
Labels: stale-exempt

#998 File Transfer Updates + RTD Revision
  CHANGELOG.md
  covalent/_file_transfer/file_transfer.py
  doc/source/concepts/concepts.rst
  doc/source/how_to/orchestration/file_transfers_for_workflows.ipynb
  tests/covalent_tests/file_transfer/strategies/base_strategy_test.py
  tests/functional_tests/file_transfer_test.py
Labels: pre-release-req

#991 trigger Slack alert for failed tests on workflow_run
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: ready for merge

#946 Remove remaining references to old topological sort
  CHANGELOG.md
  covalent/_workflow/lattice.py
  covalent/_workflow/transport.py
  tests/covalent_tests/workflow/transport_test.py
Labels: ready for merge

#988 Second attempt to fix CI webapp validation error
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: ready for merge

#1007 update conditions on the pre-release and stable releases
  .github/workflows/release.yml
  CHANGELOG.md
Labels: devops

#959 removing while true in get_result
  CHANGELOG.md
  covalent/__init__.py
  covalent/_dispatcher_plugins/local.py
  covalent/_results_manager/results_manager.py
  covalent/_results_manager/wait.py
  covalent_dispatcher/_service/app.py
  doc/source/tutorials/machine_learning/Covalent_pennylane_Iris_classification.ipynb
  doc/source/tutorials/machine_learning/Covalent_pennylane_Parity_classifier.ipynb
  doc/source/tutorials/machine_learning/Ensemble_pennylane.ipynb
  doc/source/tutorials/machine_learning/Kernel_pennylane.ipynb
  doc/source/tutorials/machine_learning/autoencoders.ipynb
  doc/source/tutorials/machine_learning/classical_quantum_svm.ipynb
  doc/source/tutorials/machine_learning/mnist_classifier.ipynb
  doc/source/tutorials/machine_learning/pennylane_hybrid.ipynb
  doc/source/tutorials/machine_learning/qaoa_maxcut.ipynb
  doc/source/tutorials/machine_learning/quantum_embedding_kernel.ipynb
  doc/source/tutorials/quantum_chemistry/nitrogen_copper_interaction.ipynb
  doc/source/tutorials/quantum_gravity/spacetime_classification.ipynb
  tests/covalent_dispatcher_tests/_service/app_test.py
  tests/covalent_tests/results_manager_tests/results_manager_test.py
Labels: stale-exempt, ready for merge

#904 Conda release
  .github/workflows/conda_build.yml
  .github/workflows/condabuild.yml
  .github/workflows/release.yml
  CHANGELOG.md
  meta.yaml
Labels: Team West, Stale, pre-release-req

#996 Rtd awsecs executor
  CHANGELOG.md
  covalent/_workflow/depsbash.py
  covalent/_workflow/depscall.py
  covalent/_workflow/depspip.py
  doc/requirements.txt
  doc/source/_static/Covalent_Local_Microservices.png
  doc/source/api/cli.rst
  doc/source/api/config.rst
  doc/source/api/covalent.rst
  doc/source/api/data_transfers.rst
  doc/source/api/deps.rst
  doc/source/api/dispatcher.rst
  doc/source/api/electrons.rst
  doc/source/api/executers/AWS_ECS.jpg
  doc/source/api/executers/awsecs.rst
  doc/source/api/executers/baseasync.rst
  doc/source/api/executers/basesync.rst
  doc/source/api/executers/cova_archi.png
  doc/source/api/executers/dask.rst
  doc/source/api/executers/index.rst
  doc/source/api/executers/local.rst
  doc/source/api/executers/slurm.rst
  doc/source/api/executers/ssh.rst
  doc/source/api/index.rst
  doc/source/api/lattice.rst
  doc/source/api/leptons.rst
  doc/source/api/microservices/microservices.rst
  doc/source/api/results.rst
  doc/source/conf.py
  doc/source/how_to/execution/execute_individual_electron.ipynb
  doc/source/index.rst
  doc/source/plugins.rst
Labels: documentation, cloud, stale-exempt, pre-release-req

#990 Rtd lambda executor
  CHANGELOG.md
  doc/requirements.txt
  doc/source/api/api.rst
  doc/source/api/executers/AWS_Lambda.jpg
  doc/source/api/executers/awslambda.rst
  doc/source/api/executers/index.rst
Labels: documentation, stale-exempt, ready for merge, pre-release-req

#997 Rtd braket executor
  CHANGELOG.md
  doc/requirements.txt
  doc/source/api/executors/AWS_Braket.jpg
  doc/source/api/executors/AWS_ECS.jpg
  doc/source/api/executors/AWS_Lambda.jpg
  doc/source/api/executors/awsbraket.rst
  doc/source/api/executors/awsecs.rst
  doc/source/api/executors/awslambda.rst
  doc/source/api/executors/baseasync.rst
  doc/source/api/executors/basesync.rst
  doc/source/api/executors/cova_archi.png
  doc/source/api/executors/dask.rst
  doc/source/api/executors/index.rst
  doc/source/api/executors/local.rst
  doc/source/api/executors/slurm.rst
  doc/source/api/executors/ssh.rst
  doc/source/api/index.rst
  doc/source/plugins.rst
Labels: documentation, stale-exempt, pre-release-req

#934 Added DB command to RTD API section
  CHANGELOG.md
  covalent_dispatcher/_cli/service.py
  covalent_dispatcher/_service/app_dask.py
  doc/source/api/api.rst
  doc/source/api/cli.rst
  doc/source/api/executors/awsbatch.rst
  doc/source/api/executors/awsbraket.rst
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: ready for review, Team West, Stale, pre-release-req

#999 Update covalent logs cli
  CHANGELOG.md
  covalent_dispatcher/_cli/service.py
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: improvement

#1116 setup load test directory with workflows and locustfiles; update requ…
  .github/workflows/license.yml
  CHANGELOG.md
  tests/load_tests/__init__.py
  tests/load_tests/locustfiles/__init__.py
  tests/load_tests/locustfiles/basic.py
  tests/load_tests/workflows/__init__.py
  tests/load_tests/workflows/horizontal.py
  tests/load_tests/workflows/identity.py
  tests/load_tests/workflows/two_node.py
  tests/requirements.txt
Labels: test
