Repository AgnostiqHQ/covalent, pull requests merged in 2023-07, with the labels that each got.

#1717 bugfixes for postgres db
  CHANGELOG.md
  covalent/_shared_files/config.py
  covalent_migrations/versions/f64ecaa040d5_add_jobs_db_table.py
  covalent_ui/api/v1/data_layer/electron_dal.py
  covalent_ui/api/v1/data_layer/graph_dal.py
  covalent_ui/api/v1/data_layer/lattice_dal.py
  covalent_ui/api/v1/data_layer/summary_dal.py
  covalent_ui/api/v1/models/dispatch_model.py
Labels: bug, covalent-ui

#1711 graceful shutdown with cancellation
  CHANGELOG.md
  covalent_dispatcher/_cli/service.py
  covalent_ui/heartbeat.py
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: bug

#1731 updating doc links in readme
  CHANGELOG.md
  README.md
Labels: documentation

#1736 fixing executor data inheritance
  CHANGELOG.md
  covalent/_shared_files/defaults.py
Labels: bug

#1582 cli enhancement
  .readthedocs.yaml
  CHANGELOG.md
  build/lib/covalent_migrations/README.md
  build/lib/covalent_migrations/alembic.ini
  covalent_dispatcher/_cli/cli.py
  covalent_dispatcher/_cli/groups/db.py
  covalent_dispatcher/_cli/service.py
  covalent_dispatcher/_db/datastore.py
  covalent_dispatcher/_triggers_app/app.py
  covalent_ui/api/v1/models/dispatch_model.py
  requirements.txt
  tests/covalent_dispatcher_tests/_cli/service_test.py
Labels: feature, improvement
